INSERT INTO PET_USER VALUES(101,'Palani','Palani');

INSERT INTO PET_USER VALUES(102,'Srikanth','Srikanth');

INSERT INTO PET_USER VALUES(103,'Shivanshu','Shivanshu');


INSERT INTO PETS VALUES(1,'Jicko',4,'CH', 101);

INSERT INTO PETS VALUES(2,'Lola',2,'DL', 102);

INSERT INTO PETS VALUES(3,'Chacko',3,'BL', 103);